
local module = {
    LastNames = {
        "Abrams",
        "Abramson",
        "Adams",
        "Anders",
        "Anderson",
        "Anderssen",
        "Andreason",
        "Andrade",
        "Baldurson",
        "Barber",
        "Bennet",
        "Black",
        "Boyd",
        "Bush",
        "Carver",
        "Carter",
        "Campbell",
        "Clinton",
        "Danielson",
        "Donner",
        "Delbert",
        "Dell",
        "Egelston",
        "Ebert",
        "Eisenhower",
        "Ellis",
        "Ellison",
        "Ethelstan",
        "Green",
        "Grant",
        "Grey",
        "Grimm",
        "Harvey",
        "Handel",
        "Haight",
        "Heinrich",
        "Henriksen",
        "Hasselhoff",
        "Halvardsen",
        "Hill",
        "Harrison",
        "Hoff",
        "Hoover",
        "Ingridsen",

        "Jensen",
        "Jenson",
        "Johnson",
        "Johansson",
        "Kennedy",
        "Klein",
        "Kleist",
        "Larson",
        "Larsen",
        "Lincoln",
        "McMahon",
        "Mikkelson",
        "Nelson",
        "Neilson",
        "Neilsen",
        "Nixon",
        "O'Neil",
        "O'Hare",
        "Ostler",
        "O'Toole",
        "Paulson",
        "Pratt",
        "Quest",
        "Quist",
        "Quisling",
        "Rasmussen",
        "Ragnarsson",
        "Reagan",
        "Roosevelt",
        "Roberts",
        "Robertson",
        "Rockefeller",
        "Schlessinger",
        "Stevenson",
        "Stoddemeyer",
        "Taft",
        "Taylor",
        "Tanner",
        "Trevino",
        "Tripp",
        "Talbott",
        "Torgersen",
        "Truman",
        "Vickers",
        "Vanderhaus",
        "VanBuren",
        "Wagner",
        "Walker",
        "Washington",
        "White",
        "Wilson",
    },
    Suffixes = {
        "Jr.",
        "III",
        "Sr."
    },
    
}


return module



